export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'

export const SET_LOCATIONS_AND_PRACTICES = 'SET_LOCATIONS_AND_PRACTICES'
export const SET_QUALIFICATIONS = 'SET_QUALIFICATIONS'
export const ADD_LOCATION = 'ADD_LOCATION'
export const ADD_PRACTICE = 'ADD_PRACTICE'
export const CLEAR_DATA = 'CLEAR_DATA'

export const SET_ERROR = 'SET_ERROR'
